# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='made before desc', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninjas_app.Dojos'),
        ),
    ]
