# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_auto_20170720_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default='added before reverted'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
